#!/usr/bin/env bash

declare __PROGNAME="${0##*/}"

default_test_file="${test_file:-spec/tests.sh}"

declare -a failures=()
declare -a successes=()
declare total_test_num=0
declare pass_test_num=0
declare fail_test_num=0
declare DEBUG=
declare PRINT_SUMMARY=1


not() {
	! "$@"
}

setup() {
	:
}

teardown() {
	:
}

test_package_signature() {
	export ERROR_LOG_FILE="error-$(echo "$*" | sha1sum | cut -d ' ' -f 1).log"
	local version="${1}"; shift
	local fpr="${1:?Missing fingerprint}"
	local archive_name="${2}"
	local zip_tar="${3}"
	run_test \
		"${ERROR_LOG_FILE}" \
		"Expected signature for version \e[1m${version}\e[22m to be signed by '\e[1m${fpr}\e[22m'" \
		signature_fingerprint_is "${fpr}" "${version}" "${archive_name}" "${zip_tar}"
}

warn() {
	>&2 echo "$@"
}

debug() {
	if [[ -n "${DEBUG:-}" ]]; then
		>&2 echo "[debug] $*"
	fi
}

signature_fingerprint_is() {
	local fpr="${1:?Missing fingerprint}"; shift
	local version="${1:?Missing version}"; shift
	local archive_name="${1}"; shift
	local zip_tar="${1}"

	local has_zip
	local has_tar

	if [[ -n "${zip_tar}" ]]; then
		if [[ "${zip_tar}" = *z* ]]; then
			has_zip=1
		fi

		if [[ "${zip_tar}" = *t* ]]; then
			has_tar=1
		fi
	fi

	local cmd=(
		./rel-sign.sh
		-V
		-r rnpgp/rnp
		-v "${version}"
		--gpg
		verify-remote
		)

	if [[ -n "${has_zip}" ]]; then
		cmd+=(-z "${archive_name}.zip")
	fi

	if [[ -n "${has_tar}" ]]; then
		cmd+=(-t "${archive_name}.tar.gz")
	fi

	debug will run: "${cmd[@]}"
	assert_eq "${fpr}" \
		"$(check_gpg_fpr_eq "${fpr}" "${cmd[@]}")"
}

check_gpg_fpr_eq() {
	local fpr="${1}"; shift

	# Grep using C locale to standardize output
	export LANG=C
	"$@" 2> >(tee -a "${ERROR_LOG_FILE}") | \
		command sed '/using.*key/!d; s/^.* //' | \
		command uniq | \
		command grep "${fpr}"
}

assert_eq() {
	local expected="${1}"; shift
	local actual="${1}"

	if [[ "$expected" = "$actual" ]]
	then
		:
	else
		warn "Expected \`${expected}\` but got \`${actual}\`."
		false
	fi
}



run_test() {
	local error_log_file="${1?:Missing error log file}"
	shift
	local expectation_message="${1?:Missing expectation message}"
	shift
	local -a cmd=("$@")
	set +e
	"$@" >/dev/null
	local rv=$? || :
	# set -e

	((++total_test_num)) || :

	local test_raw_name="${FUNCNAME[1]}"
	if [[ "${FUNCNAME[1]}" = _* ]]
	then
		test_raw_name="${FUNCNAME[2]}"
	fi
	local test_name="${test_raw_name#test_}"
	test_name="${test_name//_/ }"

	local serialized_result="${test_name}::: ${expectation_message}:: ${error_log_file}::::${cmd[*]}"

	if [[ $rv = 0 ]]
	then
		((++pass_test_num)) || :
		successes+=("${serialized_result}")
		printf '\e[32m.\e[m'
	else
		((++fail_test_num)) || :
		failures+=("${serialized_result}")
		printf '\e[31mF\e[m'
	fi
	return $rv
}

print_summary() {
	if [[ -z "${PRINT_SUMMARY:-}" ]]
	then
		return
	fi

	local success_idx=0
	local failure_idx=0
	echo
	echo "=== Summary ==="
	if [[ "${#successes[@]}" -gt 0 ]]
	then
		echo
	fi

	for passed_test in "${successes[@]}"
	do
		((success_idx++)) || :
		local test_name___expectation_message__output="${passed_test%::::*}"
		local test_cmd="${passed_test#*::::}"
		local test_name="${test_name___expectation_message__output%::: *}"
		local expectation_message__output="${test_name___expectation_message__output#*::: }"
		local expectation_message="${expectation_message__output%:: *}"
		local cmd_output="${expectation_message__output#*:: }"
		printf "   \e[32;1m%b\e[22m passed\e[m\n" "${expectation_message}"
		if [[ -r "${cmd_output}" ]]; then
			printf "   \e[mOutput:\n"
			while IFS= read -r line; do
				printf "            \e[32m%s\e[m\n" "${line}"
			done < "${cmd_output}"
			rm "${cmd_output}"
		fi
		echo
	done

	if [[ "${#failures[@]}" -gt 0 ]]
	then
		echo
	fi

	for failed_test in "${failures[@]}"
	do
		((failure_idx++)) || :
		local test_name___expectation_message__output="${failed_test%::::*}"
		local test_cmd="${failed_test#*::::}"
		local test_name="${test_name___expectation_message__output%::: *}"
		local expectation_message__output="${test_name___expectation_message__output#*::: }"
		local expectation_message="${expectation_message__output%:: *}"
		local cmd_output="${expectation_message__output#*:: }"

		printf "\e[1mFailure #%d:\e[22m\n" "${failure_idx}"
		printf "   \e[31;1m%b\e[22m failed\e[m\n\n" "${test_name}"
		printf "   \e[34m%b\e[m\n" "${expectation_message}"
		printf "   \e[mCommand: \e[31m%s\e[m\n" "${test_cmd}"

		if [[ -r "${cmd_output}" ]]; then
			printf "   \e[mOutput:\n"
			while IFS= read -r line; do
				printf "            \e[31m%s\e[m\n" "${line}"
			done < "${cmd_output}"
			rm "${cmd_output}"
		fi
		echo
	done
	printf 'Total: %s test(s), %s passed, %s failed\n' "${total_test_num}" "${pass_test_num}" "${fail_test_num}"
}

trap print_summary EXIT

return_status() {
	! (( fail_test_num ))
}

# Print help message
print_help() {
	printf "Run tests against rel-sign.
\e[1;4mUsage\e[m
    \e[3m${__PROGNAME}\e[m \e[4mOPTIONS...\e[m \e[4m[TEST_FILES,...]\e[m

\e[1;4mOptions\e[m
    -h, --help      - show this help message and abort
    -d, --debug     - dump commands which are executed
"
	echo
}

# Extract parameters
parse-opts() {
	while [[ $# -gt 0 ]]; do
		case "$1" in
			--debug|-d)
				DEBUG=1
				QUIET=
				;;
			--help|-h)
				PRINT_SUMMARY=
				print_help
				exit 0
				;;
			--*|-*)
				PRINT_SUMMARY=
				warnp "Invalid argument: %s\nUse --help or -h to get list of available arguments.\n" "$1"
				exit 1
				;;
		esac
		shift
		((OPTIND++))
	done
}

OPTIND=1

main() {
	parse-opts "$@"
	shift $((OPTIND - 1))

	setup
	if [[ $# -gt 0 ]]
	then
		for test_file in "$@"
		do
			. "${test_file}"
		done
	else
		. "${default_test_file}"
	fi
	teardown
	return_status
}

main "$@"
