name: Check signatures

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 0,3'

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check signatures
        run: scripts/run_tests
